.github/workflows/cypress-frontend.yaml, apps/frontend/cypress.json, apps/frontend/cypress/integration/1-getting-started/test.spec.ts
CI frontend tests with cypress (component and integration)
Trigger:
- pull request to main, develop
- push to "apps/frontend" and "cypress-frontend.yaml"
=> Frontend CI Tests

.github/workflows/cypress-frontend.yaml, apps/frontend/cypress.json, apps/frontend/cypress/integration/1-getting-started/test.spec.ts, apps/frontend/package.json
Closes [GPF-83](https://spacifik.atlassian.net/browse/GPF-83?atlOrigin=eyJpIjoiODI1NzhjNDI1MGYzNGFiYWI1MzcxNjVjOGRkOTNlYTYiLCJwIjoiaiJ9)
Changes
---
- updated frontend ports to 8100
=> [GPF-83]: Updated frontend ports

apps/utr-backend/package-lock.json, apps/utr-backend/package.json, apps/utr-backend/prisma/schema.prisma
Closes [UTR-26](https://spacifik.atlassian.net/jira/software/projects/UTR/boards/4?selectedIssue=UTR-26) and [UTR-31](https://spacifik.atlassian.net/jira/software/projects/UTR/boards/4?selectedIssue=UTR-31)
- installed prisma dependency in utr-backend
- initialized prisma project in utr-backend
- adjusted schema.prisma file to work with postgres and .env file
- added first scheme for entries
=> [UTR-26]: Initialize Prisma in UTR-Backend & add first scheme for entries

apps/utr-backend/openapi.yaml, apps/utr-backend/prisma/schema.prisma
Closes: [UTR-32](https://spacifik.atlassian.net/jira/software/projects/UTR/boards/4?selectedIssue=UTR-32)
Added API definition for the UTR-Backend which can be viewed via the yaml file. VScode extension "OpenAPI (Swagger) Editor" by 42Crunch is a great extension to view the rendered API Definition. Also deleted price and rating from the prisma schema.
- Added openapi.yaml file
- Adapted prisma schema to match api definition
=> [UTR-32] API definition utr backend

packages/storybook/.storybook/main.js
Closes: [GPF-107](https://spacifik.atlassian.net/browse/GPF-107)
better configurations for Typescript:
https://storybook.js.org/docs/react/configure/typescript
- added Typescript handling, in .storybook/main.js.
=> [GPF-107]: boyscout storybook speedup

apps/utr-backend/.env, apps/utr-backend/config/winston.ts, apps/utr-backend/openapi.yaml, apps/utr-backend/package-lock.json, apps/utr-backend/package.json, apps/utr-backend/src/index.ts
Closes: [UTR-40](https://spacifik.atlassian.net/jira/software/projects/UTR/boards/4?selectedIssue=UTR-40)
Die .env Datei musste erneuert werden, da @konstantin-spiess mit dem Merge von #5 im commit `Merge branch 'develop' into GPF-44` ausversehen die .env auf einen alten Stand gesetzt hatte. Jetzt stimmt der Backend-Port auch wieder.
Winston wurde als logger hinzugefügt im utr-be und kann nach dem importieren der config datei (config/winston) mit debug, info, warn und error benutzt werden. 
Die API wurde wie am Sonntag dem 28.11. besprochen angepasst.
- updated .env in utr-be
- added winston as a logger in utr-be
- added required tag for address in utr-be api definition
- removed distance from search query in utr-be api definition
=> [UTR-40] Logger UTR Backend

.github/workflows/backend-deploy.yaml
Closes: [GPF-136](https://spacifik.atlassian.net/browse/GPF-136)
=> [GPF-136] Fix cloud run description step

.github/workflows/backend-deploy.yaml, deploy/staging.tf
=> [GPF-136] Fix cloud run secret permissions

deploy/main.tf, deploy/staging.tf
Closes: [GPF-137](https://spacifik.atlassian.net/jira/software/projects/GPF/boards/3?selectedIssue=GPF-137)
=> [GPF-137] Add domain mapping to terraform

.github/workflows/backend-deploy.yaml
=> Gpf 153 frontend bucket deploy

packages/ui/src/styles/tokens.scss
Closes: [GPF-154](https://spacifik.atlassian.net/browse/GPF-154)
Ich habe am Anfang aller Variablen den Typ hinzugefügt. So kann man mit Autocomplete sich alle verfügbaren Variablen von einer Kategorie (z.B. size) anzeigen lassen.
- added size tokens
- consistent naming
=> [GPF-154] Design Tokens Size

packages/ui/src/styles/tokens.scss
Closes: [GPF-157](https://spacifik.atlassian.net/jira/software/projects/GPF/boards/3?selectedIssue=GPF-157)
=> [GPF-157] update design tokens

deploy/main.tf
Closes: [UTR-54](https://spacifik.atlassian.net/jira/software/projects/UTR/boards/4?selectedIssue=UTR-54)
Ich hab das so richtig gemacht in der Terraform Datei oder? Bitte einmal schauen ob ich das richtig verstanden hatte.
- activated Maps Javascript API & Places API in Terraform
=> [UTR-54] Activate Maps Javascript API & Places API 

apps/utr-backend/src/endpoints/entry/EntryRoute.ts, apps/utr-backend/src/endpoints/entry/EntryService.ts, apps/utr-backend/src/endpoints/utils/ApplicationError.ts, apps/utr-backend/src/endpoints/utils/AuthenticationUtils.ts, apps/utr-backend/src/endpoints/utils/EntryUtils.ts, apps/utr-backend/src/index.ts
Closes: [UTR-61](https://spacifik.atlassian.net/jira/software/projects/UTR/boards/4?selectedIssue=UTR-61)
Sollte eigentlich alles trivial sein zum reviewen, da ja oftmals auch gemeinsam etwas durchgesprochen schon. Gerne nochmal schnell rüber schauen :D
- Error-Handling is now done using a custom Error class that provides an error code alongside the standard message
- Differenciates between this type of error and others in EntryRoute
- Now using the Array.map function to return a subset of attributes returned by prisma requests in the http response
- Put-Route now only returns 200 instead of the updatedEntry (as specified in openap.yaml)
=> [UTR-61] Error-Handling überarbeiten

apps/utr-backend/openapi.yaml, apps/utr-backend/package-lock.json, apps/utr-backend/package.json, apps/utr-backend/src/app.ts, apps/utr-backend/src/endpoints/entry/EntryRoute.ts, apps/utr-backend/src/endpoints/entry/EntryService.ts, apps/utr-backend/src/endpoints/utils/EntryUtils.ts, apps/utr-backend/src/tests/tests_restclient/entry_tests/create-tests.http, apps/utr-backend/src/tests/tests_restclient/entry_tests/delete-tests.http, apps/utr-backend/src/tests/tests_restclient/entry_tests/get-tests.http, apps/utr-backend/src/tests/tests_restclient/entry_tests/search-tests.http, apps/utr-backend/src/tests/tests_restclient/entry_tests/update-tests.http
Closes: [UTR-46](https://spacifik.atlassian.net/jira/software/projects/UTR/boards/4?selectedIssue=UTR-46)
- When we finish implementing the backend, any remaining traces of createMany and parseToBoolean will be deleted if it is confirmed, that they are no longer needed by then.
- Added Express OpenAPI Validator in app.tsx
- Made some very minor changes in openapi.yaml to fit implementation
- Added Authorization Header to some test requests to fit yaml specification
- Removed/Commented out CreateMany + Route + Test-Request because it doesnt fit specification
- Commented out parseToBoolean as it is probably not necessary anymore
=> [UTR-46] Express OpenAPI Validator einbinden

apps/frontend/src/pages/Gruendung/Gruendung.module.scss, apps/frontend/src/pages/Gruendung/subcomponents/CompletedToggle/CompletedToggle.module.scss, packages/ui/src/styles/base.scss
Closes: GPF-156
- moved styles from the Gruendung.module.scss to the base.scss and defined styles and margins for all headings
=> [GPF-156] Defined heading and p sizes plus margins

apps/frontend/src/App.tsx, apps/frontend/src/pages/Search/UTRSearch.tsx, apps/frontend/src/pages/Search/subcomponents/HeadlineUTR/Headline.module.scss, apps/frontend/src/pages/Search/subcomponents/HeadlineUTR/Headline.tsx, apps/frontend/src/pages/Search/subcomponents/InstructionUTR/Instruction.module.scss, apps/frontend/src/pages/Search/subcomponents/InstructionUTR/Instruction.tsx, apps/frontend/src/pages/Search/subcomponents/SearchFormUTR/SearchForm.module.scss, apps/frontend/src/pages/Search/subcomponents/SearchFormUTR/SearchForm.tsx, apps/frontend/src/pages/Search/subcomponents/SearchResultsListUTR/SearchResult.module.scss, apps/frontend/src/pages/Search/subcomponents/SearchResultsListUTR/SearchResult.tsx, apps/frontend/src/pages/Search/subcomponents/SearchResultsListUTR/SearchResultsList.module.scss, apps/frontend/src/pages/Search/subcomponents/SearchResultsListUTR/SearchResultsList.tsx
Closes: UTR-60
- Kann das Ticket nicht mehr verlinken, weil noch aus dem schon abgeschlossenen Sprint. Ansonsten dürfte alles relativ simpel sein. Kann natürlich sein das der Code an manchen Stellen noch etwas ineffizient geschrieben ist, z.B. hinsichtlich Ordnerstruktur/Imports, Verwendung der Schachtelung bei SCSS, den handleFunctions u.ä., weil mir die Best Practices fehlen, sollte sonst aber fine sein.
- Ansonsten ist die Form noch nicht responsive, die Funktionalität mit dem Backend noch nicht gegeben und es fehlt noch eine subcomponente in form eines Texts das sagt, für welche Params gesucht wurde, aber dort macht Paul dann mit diesem Stand in main eben auch weiter wenn er seine Adresskomponente einbaut.
- Den DemoAsyncContent in App.tsx habe ich einkommentiert, da er …
=> [UTR-60] Begin UTR Frontend

apps/utr-backend/openapi.yaml, apps/utr-backend/src/endpoints/entry/EntryRoute.ts, apps/utr-backend/src/endpoints/entry/EntryService.ts, apps/utr-backend/src/tests/tests_restclient/entry_tests/search-tests.http
Closes: [DLR-70](https://spacifik.atlassian.net/jira/software/projects/DLR/boards/4?selectedIssue=DLR-70)
@SkyGuardian42 Please look if the way the pagination is implemented looks good to you. Or if you would change something.
- added ordering by distance for the return array
- added pagination for the search -> new query parameter for the search
=> [DLR-70] Search Route: Order by and pagination

apps/utr-backend/docker-compose.yml, deploy/dlr_production.tf, deploy/dlr_staging.tf, deploy/gpf_production.tf, deploy/gpf_staging.tf, deploy/main.tf, deploy/variables.tf
Closes: [GPF-140](https://spacifik.atlassian.net/jira/software/projects/GPF/boards/3?selectedIssue=GPF-140)
=> [GPF-140] deployment for DLR

apps/frontend/src/components/Footer/Footer.module.scss, apps/frontend/src/components/Footer/Footer.tsx, apps/frontend/src/pages/Index/Index.module.scss
Closes: [GPF-183](https://spacifik.atlassian.net/jira/software/projects/GPF/boards/3/backlog?selectedIssue=GPF-183)
Fix this:
=> [GPF-183] Fix landing page styling and footer links

apps/frontend/src/pages/Demo/DemoAuth.tsx
=> Fix demoAuth

apps/frontend/package-lock.json, apps/frontend/src/components/Header/Header.module.scss
- header blur bg transition clip path instead of height
=> [GPF-175] Header performance

apps/frontend/src/contexts/Gruendung/Gruendung.tsx, packages/api/api.schemas.ts, packages/api/api.ts, packages/api/axios.ts, packages/api/index.ts, packages/api/orval.config.ts
=> Fix Axios calls

apps/frontend/src/steps/302_Entscheidung_Gesellschaftsvertrag.md
Closes: [GPF-212](https://spacifik.atlassian.net/browse/GPF-212)
- falsche Formatierung gefixt:
=> [GPF-212] Boyscout: checklist fixed

apps/utr-backend/openapi.yaml, apps/utr-backend/src/endpoints/entry/EntryRoute.ts, apps/utr-backend/src/endpoints/entry/EntryService.ts
Fixing some errors after merging in dlr-backend.
- set ownedBy to nullable
- removed duplicated verified
=> fixing dlr-backend

apps/frontend/src/contexts/Gruendung/Gruendung.tsx
Closes: GPF-123
- added in localStorage.clear();
=> [GPF] Clear local storage on company delete

apps/frontend/src/pages/Gruendung/Gruendung.tsx, apps/frontend/src/steps/connections.ts
Closes: GPF
- unlocked the GMBH button on /gruendung,
- changes UG to Firma in connections.ts for correct titles when having selected the gmbh path
=> [GPF] Unlocked GMBH on /gruendung, changed UG to Firma for correct titles

apps/frontend/src/pages/Adminpanel/Adminpanel.tsx, apps/frontend/src/pages/Adminpanel/subcomponents/CreateFormAdmin/CreateFormAdmin.tsx, apps/frontend/src/pages/Adminpanel/subcomponents/EditFormAdmin/EditFormAdmin.tsx, apps/frontend/src/pages/Adminpanel/subcomponents/GetAllResultList/GetAllResult.module.scss, apps/frontend/src/pages/Adminpanel/subcomponents/GetAllResultList/GetAllResult.tsx, apps/frontend/src/pages/Profil/Profil.module.scss, apps/frontend/src/pages/Profil/Profil.tsx, apps/frontend/src/pages/Profil/subcomponents/CreateDienstleister.module.scss, apps/frontend/src/pages/Profil/subcomponents/CreateDienstleister.tsx, apps/frontend/src/pages/Profil/subcomponents/DienstleisterProfil.tsx, apps/frontend/src/pages/Profil/subcomponents/EditDeleteDienstleister.module.scss, apps/frontend/src/pages/Profil/subcomponents/EditDeleteDienstleister.tsx, apps/frontend/src/pages/SearchDLR/DLRSearch.tsx, apps/frontend/src/pages/SearchDLR/subcomponents/SearchResultsListDLR/SearchResult.tsx, apps/utr-backend/openapi.yaml, apps/utr-backend/src/app.ts
Closes: [DLR-113](https://spacifik.atlassian.net/jira/software/projects/DLR/boards/4?selectedIssue=DLR-113)
- Hintergrund-Design vom öffentlichen Dienstleisterprofil gefixt
- Alle Routen laufen jetzt über /dlr/ statt localhost -> im Frontend getestet
- Kleinere Anpassungen am Dienstleisterprofil Style
=> [DLR-113] Routen fixen & Dienstleisterprofil-Styling

apps/frontend/src/components/Header/Header.tsx, apps/frontend/src/components/Menu/Menu.tsx, apps/frontend/src/components/MobileMenu/MobileMenu.tsx, apps/frontend/src/pages/Profil/Profil.tsx
Closes: GPF-213
- updated dlr profile link to menu and mobile menu
- added dlr adminpanel link to menu and mobile menu
=> [GPF-213] Update Header Links DLR

apps/frontend/src/components/TextBlock/TextBlock.module.scss
Closes: GPF-203
- fixed font-sizes and layout
=> [GPF-203] Mobile fix legal pages

apps/frontend/src/pages/Profil/Profil.tsx
Closes: GPF
-  Fixed state names for profile
=> [GPF] Fixed state names for profile

apps/frontend/src/pages/Index/Index.module.scss
Closes: [GPF-201](https://spacifik.atlassian.net/jira/software/projects/GPF/boards/3?selectedIssue=GPF-201)
Fixed on Firefox:
=> [GPF-201] Fix firefox bug on landing page

apps/backend/prisma/migrations/20220206113113_cascade_deletes/migration.sql, apps/backend/prisma/schema.prisma
Closes: [GPF-214](https://spacifik.atlassian.net/jira/software/projects/GPF/boards/3?selectedIssue=GPF-214)
Fixed by adding on delete cascade to prisma schema
=> [GPF-214] Fix company deletion

apps/frontend/src/pages/Gruendung/$task.tsx, apps/frontend/src/pages/Index/Index.tsx
Fixed regex crash
Fixed landing page video autoplay
=> IOS Hotfix

apps/frontend/src/components/TaskList/DecisionNode/DecisionNode.module.scss
- fixed position of corners
- fixed border width
=> [GPF-245] fix mobile navigation decision node

apps/frontend/src/components/TaskList/Decision/Decision.tsx, apps/frontend/src/components/TaskList/DecisionNode/DecisionNode.module.scss, apps/frontend/src/components/TaskList/DecisionNode/DecisionNode.tsx, apps/frontend/src/components/TaskList/EmptyNode/EmptyNode.tsx, apps/frontend/src/components/TaskList/Nodes/Nodes.tsx, apps/frontend/src/components/TaskList/TaskList.module.scss, apps/frontend/src/components/TaskList/TaskList.tsx, apps/frontend/src/components/TaskList/TaskNode/TaskNode.module.scss, apps/frontend/src/components/TaskList/TaskNode/TaskNode.tsx, apps/frontend/src/contexts/Gruendung/Gruendung.tsx, apps/frontend/src/pages/Gruendung/$task.tsx, apps/frontend/src/pages/Gruendung/Gruendung.module.scss, apps/frontend/src/pages/Gruendung/Gruendung.tsx
Closes: [GPF-246](https://spacifik.atlassian.net/browse/GPF-246)
- new navigation design
=> [GPF-246] Navigation Design

apps/frontend/src/components/TaskList/Decision/Decision.tsx, apps/frontend/src/components/TaskList/DecisionNode/DecisionNode.tsx, apps/frontend/src/components/TaskList/EmptyNode/EmptyNode.tsx, apps/frontend/src/components/TaskList/Nodes/Nodes.tsx, apps/frontend/src/components/TaskList/TaskList.tsx, apps/frontend/src/components/TaskList/TaskNode/TaskNode.tsx, apps/frontend/src/contexts/Gruendung/Gruendung.tsx, apps/frontend/src/pages/Gruendung/Gruendung.tsx
Closes: [GPF-247](https://spacifik.atlassian.net/browse/GPF-247)
- rerender arrows on nodes change
- added data-disabled to nodes
- added calculation for data-disabled
- fixed redirect to empty nodes
=> [GPF-247] Navigation Logic

deploy/dlr_production.tf, deploy/gpf_production.tf
Closes: GPF-[252](https://spacifik.atlassian.net/jira/software/projects/GPF/boards/3?selectedIssue=GPF-252)
Changes:
- Sets minimum instance count to 1
=> [GPF-252] Add minimum instances

packages/ui/src/styles/reset.scss
Closes parts of [GPF-255](https://spacifik.atlassian.net/jira/software/projects/GPF/boards/3?selectedIssue=GPF-255)
Before:
After:
=> [GPF-255] Fix safari button bug

apps/frontend/src/pages/Gruendung/$task.tsx
Closes: [GPF-260](https://spacifik.atlassian.net/jira/software/projects/GPF/boards/3?selectedIssue=GPF-260)
Changes:
Automatically scroll after user clicks "weiter"
=> [GPF-260] Auto scroll on navigation

apps/frontend/src/pages/Index/Index.module.scss, apps/frontend/src/pages/Index/Index.tsx
Closes: [GPF-274](https://spacifik.atlassian.net/jira/software/projects/GPF/boards/3?selectedIssue=GPF-274)
- add parallax to second image
- remove console.logs
=> [GPF-274] Landing Page Tweaks

apps/frontend/src/components/AddressField/AddressField.tsx
Closes: [GPF-268](https://spacifik.atlassian.net/jira/software/projects/GPF/boards/3?assignee=61701b6126a54000712e7f01&selectedIssue=GPF-268)
- changed autocomplete field types to geocode - supports cities etc
=> [GPF-268] DLR-search support for cities, zip codes etc

apps/frontend/src/components/DienstleisterRadioTiles/DienstleisterRadioTiles.module.scss, apps/frontend/src/components/DienstleisterRadioTiles/DienstleisterRadioTiles.tsx, apps/frontend/src/pages/SearchDLR/DLRSearch.tsx, apps/frontend/src/pages/SearchDLR/subcomponents/AddressWarning/AddressWarning.module.scss, apps/frontend/src/pages/SearchDLR/subcomponents/HeadlineDLR/Headline.module.scss, apps/frontend/src/pages/SearchDLR/subcomponents/SearchFormDLR/SearchForm.module.scss, apps/frontend/src/pages/SearchDLR/subcomponents/SearchFormDLR/SearchForm.tsx
Closes: [GPF-263](https://spacifik.atlassian.net/jira/software/projects/GPF/boards/3?assignee=70121%3A5f7ba5dc-bbe1-4abd-9436-b8dc3ec94ec1&selectedIssue=GPF-263)
- _Wowww ein Ticket pro PR???? Wer ist dieser Ersteller und was hat er mit Kai gemacht?_
- Bisher nur auf Chrome getestet (GitHub Student Application für BrowserStack ist noch in Review)
- Bisher nur in der öffentlichen Suche drin, Einfügen in Create/Edit Public o. im Adminpanel dürfte durch die Implementierung als Komponente aber ziemlich trivial sein falls gewünscht
- Altes Dropdown-Menü in der öffentlichen Suche rausgeschmissen
- Neues Radio Tiles Design als Komponente implementiert und eingefügt
- Sollte responsive sein und Fehlermeldung bei fehlender Auswahl anzeigen
- Kleine Größenanpassung der AdressWarning
- Suchen Button …
=> [GPF-263] Dienstleister-Suche Radio Tiles Design

apps/frontend/src/pages/GesellschaftsformDecisionPage/GesellschaftsformDecision.module.scss, apps/frontend/src/pages/GesellschaftsformDecisionPage/GesellschaftsformDecision.tsx
Closes: [GPF-200](https://spacifik.atlassian.net/jira/software/projects/GPF/boards/3?selectedIssue=GPF-200)
=> [GPF-200] Landing Page -> CTA-Seite optimieren

apps/frontend/src/components/TaskList/TaskList.tsx
Closes: GPF-123
- fixed tilted arrows
=> [GPF-96] Fix tilted arrows

.github/workflows/deploy.yaml
=> fix secret value

apps/frontend/src/pages/Datenschutzerklaerung/Datenschutzerklaerung.tsx, apps/frontend/src/pages/Impressum/Impressum.tsx
dont want any phone cold calls anymore
=> [BOYSCOUT] delete phone number
